## or in /etc/environment
export LANG=zh_CN.UTF-8
export LANGUAGE=zh_CN:en_US
export LC_CTYPE=en_US.UTF-8
export DWM="/home/song/scripts/1-shell/dwm"
GTK_IM_MODULE=xim
GTK_IM_MODULE=ibus
QT_IM_MODULE=ibus
XMODIFIERS=@im=ibus
#QT_IM_MODULE=fcitx
 #exec awesome
# GTK_IM_MODULE=fcitx
# QT_IM_MODULE=fcitx
# XMODIFIERS=@im=fcitx
 exec dwm
# exec i3

# export DESKTOP_SESSION=plasma 
# exec startplasma-x11
