#!/bin/bash
export MOONSHOT_API_KEY="sk-FFhLmfCnkHZUxGqmiZHv4secWVC7ppa1bs3doZP04VjKi0X2"
## ofd文件转pdf
ofd2pdf(){
 echo 'ofd 2 pdf by pymupdf'
  condaup
  python -c "from mypandoc import ofd_to_pdf;ofd_to_pdf('$1')"
  condadown
}

pdf2png() {
  currentdir=$(pwd)
  png_dir=$currentdir/png
  temp_dir="/tmp/$(date)tmp"
  basename1=$(basename ${1%.*})
  echo $basename1
  [ ! -d $temp_dir ] && mkdir $temp_dir 
  cp $1 $temp_dir
  cd $temp_dir
  mutool convert -F png $(basename $1)
  pnglist=( ./*png  )

  [ ! -d $png_dir  ] && mkdir $png_dir 
  cp *.png $png_dir
  cd $currentdir
  unset currentdir
  unset png_dir
  unset temp_dir
  unset basename1
  unset pnglist
}

pdf2text_pro() {
  currentdir=$(pwd)
  png_dir=$currentdir/png
  png_proc_dir=$currentdir/png_proc
  txt_dir=$currentdir/txt
  txt_proc_dir=$currentdir/txt_proc
  temp_dir="/tmp/$(date)tmp"
  basename1=$(basename ${1%.*})
  [ ! -d $temp_dir ] && mkdir $temp_dir 
  cp $1 $temp_dir
  cd $temp_dir
  mutool convert -F png $(basename $1)

  ## 直接ORC
  pnglist=( ./*png  )
  for png in $pnglist
  do
    tesseract $png $(basename ${png%.*})  -l chi_sim --oem 1
  done
  cat *.txt > $currentdir/${basename1}.txt
  [ ! -d txt ] && mkdir txt && mv *.txt ./txt

  ## 使用opencv预处理后再ORC
  condaup
  for png in $pnglist
  do
    python -c "from mypandoc import processed_image;processed_image('$png')"
  done
  condadown
  pngproclist=( ./*proc\.png  )
  for png_proc in $pngproclist
  do
    tesseract $png_proc $(basename ${png_proc%.*})  -l chi_sim --oem 1
  done
  cat *proc.txt > $currentdir/${basename1}proc.txt
  [ ! -d txt_proc ] && mkdir txt_proc && mv *proc.txt ./txt_proc

  # 保存文件
  [ ! -d $png_dir  ] && mkdir $png_dir 
  cp *.png $png_dir
  [ ! -d $png_proc_dir  ] && mkdir $png_proc_dir 
  cp *proc.png $png_proc_dir
  [ ! -d $txt_dir ] && mkdir $txt_dir 
  cp ./txt/*.txt $txt_dir
  [ ! -d $txt_proc_dir ] && mkdir $txt_proc_dir 
  cp ./txt_proc/*proc.txt $txt_proc_dir
  cd $currentdir
  unset currentdir
  unset png_dir
  unset txt_dir
  unset temp_dir
  unset basename1
  unset pnglist
}


pdf2text() {
  currentdir=$(pwd)
  png_dir=$currentdir/png
  txt_dir=$currentdir/txt
  temp_dir="/tmp/$(date)tmp"
  basename1=$(basename ${1%.*})
  echo $basename1
  [ ! -d $temp_dir ] && mkdir $temp_dir 
  cp $1 $temp_dir
  cd $temp_dir
  mutool convert -F png $(basename $1)
  pnglist=( ./*png  )
  for png in $pnglist
  do
    tesseract $png $(basename ${png%.*})  -l chi_sim --oem 1
  done
  echo $basename1
  cat *.txt > $currentdir/${basename1}.txt

  [ ! -d $png_dir  ] && mkdir $png_dir 
  cp *.png $png_dir
  [ ! -d $txt_dir ] && mkdir $txt_dir 
  cp *.txt $txt_dir
  cd $currentdir
  unset currentdir
  unset png_dir
  unset txt_dir
  unset temp_dir
  unset basename1
  unset pnglist
}

processed_image(){
  echo $1
  condaup
      python -c "from mypandoc import processed_image;processed_image('$1')"
  condadown

}

docx2md(){
  [ ! -d ./markdown ] && mkdir ./markdown
  docling $1 --from docx --to md --output ./markdown
}

docx2mds(){
  docpaths=("$@")
  for docpath in "${docpaths[@]}"
do
  echo $docpath
  docx2md $docpath
done
}
